"""Automatic slide deck generation.

The deck is built from the narrative, not from a fixed template, so it adapts
to whatever the data turned out to contain: a collection with no seasonal
categories gets no seasonality slide, and one with a collection failure gets a
slide about it.

python-pptx is used rather than a JavaScript generator so the whole application
is a single Python deployment with no Node runtime.
"""

import io
from typing import List

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR

from .insights import Narrative, Finding

# Palette, matching charts.py
INK = RGBColor(0x12, 0x26, 0x3A)
PRIMARY = RGBColor(0x1E, 0x4D, 0x6B)
ACCENT = RGBColor(0xD9, 0x82, 0x2B)
MUTED = RGBColor(0x8A, 0x9B, 0xA8)
LIGHT = RGBColor(0xE9, 0xEE, 0xF2)
PAPER = RGBColor(0xFF, 0xFF, 0xFF)
ON_DARK = RGBColor(0xF4, 0xF7, 0xF9)

HEAD_FONT = "Cambria"
BODY_FONT = "Calibri"

W, H = 13.333, 7.5

METHOD_NAMES = {"none": "no imputation", "class_mean": "class mean",
                "carry_forward": "carry forward", "seasonal_hold": "seasonal hold"}


def _pretty(name: str) -> str:
    return METHOD_NAMES.get(name, name.replace("_", " "))

M = 0.7                                  # margin


def _blank(prs):
    return prs.slides.add_slide(prs.slide_layouts[6])


def _bg(slide, prs, colour):
    shp = slide.shapes.add_shape(1, 0, 0, prs.slide_width, prs.slide_height)
    shp.fill.solid()
    shp.fill.fore_color.rgb = colour
    shp.line.fill.background()
    shp.shadow.inherit = False
    slide.shapes._spTree.remove(shp._element)
    slide.shapes._spTree.insert(2, shp._element)
    return shp


def _text(slide, x, y, w, h, runs, align=PP_ALIGN.LEFT, anchor=MSO_ANCHOR.TOP,
          space_after=0):
    """runs: list of dicts with text, size, bold, colour, font, italic."""
    box = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = box.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = anchor
    tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = 0
    for i, r in enumerate(runs):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.alignment = align
        p.space_after = Pt(r.get("space_after", space_after))
        if r.get("bullet"):
            p.level = 0
        run = p.add_run()
        run.text = r["text"]
        f = run.font
        f.name = r.get("font", BODY_FONT)
        f.size = Pt(r.get("size", 14))
        f.bold = r.get("bold", False)
        f.italic = r.get("italic", False)
        f.color.rgb = r.get("colour", INK)
        if r.get("line_spacing"):
            p.line_spacing = r["line_spacing"]
    return box


def _card(slide, x, y, w, h, fill=LIGHT):
    shp = slide.shapes.add_shape(5, Inches(x), Inches(y), Inches(w), Inches(h))  # rounded rect
    shp.fill.solid()
    shp.fill.fore_color.rgb = fill
    shp.line.fill.background()
    shp.shadow.inherit = False
    try:
        shp.adjustments[0] = 0.06
    except Exception:
        pass
    return shp


def _dot(slide, x, y, d, colour=ACCENT):
    shp = slide.shapes.add_shape(9, Inches(x), Inches(y), Inches(d), Inches(d))  # oval
    shp.fill.solid()
    shp.fill.fore_color.rgb = colour
    shp.line.fill.background()
    shp.shadow.inherit = False
    return shp


def _image(slide, png: bytes, x, y, w):
    return slide.shapes.add_picture(io.BytesIO(png), Inches(x), Inches(y), width=Inches(w))


# ----------------------------------------------------------------------
# Slides
# ----------------------------------------------------------------------
def slide_title(prs, nar: Narrative, label: str):
    s = _blank(prs)
    _bg(s, prs, INK)
    _dot(s, M, 1.44, 0.18, ACCENT)
    _text(s, M + 0.34, 1.36, 7, 0.35,
          [{"text": "PRICE COLLECTION ANALYSIS", "size": 12, "bold": True,
            "colour": ACCENT, "font": BODY_FONT}])
    _text(s, M, 2.05, W - 2 * M - 0.8, 2.4,
          [{"text": nar.headline, "size": 40, "bold": True, "colour": ON_DARK,
            "font": HEAD_FONT, "line_spacing": 1.08}])
    _text(s, M, 4.75, W - 2 * M - 0.8, 0.45,
          [{"text": label, "size": 15, "colour": ON_DARK}])
    _text(s, M, 5.25, W - 2 * M - 0.8, 0.5,
          [{"text": nar.subtitle, "size": 12, "colour": MUTED}])
    _text(s, M, 6.6, 9, 0.4,
          [{"text": "Generated by PriceLab. Every figure is reproducible from the "
                    "exported configuration.", "size": 10, "colour": MUTED,
            "italic": True}])
    s.notes_slide.notes_text_frame.text = (
        "Open on the headline number, then say what the collection is and over what "
        "period. Do not read the subtitle aloud, it is there for the reader.")
    return s


def slide_contents(prs, nar: Narrative, n=4):
    s = _blank(prs)
    _text(s, M, 0.55, 10, 0.7,
          [{"text": "What the data shows", "size": 34, "bold": True,
            "font": HEAD_FONT}])
    top = nar.top(n)
    y, gap, card_h = 1.55, 0.22, 1.24
    for i, f in enumerate(top):
        _card(s, M, y, W - 2 * M, card_h, LIGHT)
        _dot(s, M + 0.38, y + card_h / 2 - 0.16, 0.32, ACCENT)
        _text(s, M + 0.38, y + card_h / 2 - 0.15, 0.32, 0.3,
              [{"text": str(i + 1), "size": 13, "bold": True, "colour": PAPER}],
              align=PP_ALIGN.CENTER)
        _text(s, M + 1.0, y + 0.24, W - 2 * M - 1.6, 0.5,
              [{"text": f.headline, "size": 16, "bold": True, "colour": INK}])
        _text(s, M + 1.0, y + 0.72, W - 2 * M - 1.6, 0.4,
              [{"text": f.evidence, "size": 11, "colour": PRIMARY, "italic": True}])
        y += card_h + gap
    s.notes_slide.notes_text_frame.text = (
        "Four findings, ranked by materiality. Say each headline once and move on; the "
        "detail comes on the slides that follow.")
    return s


def slide_finding(prs, f: Finding, chart_png: bytes = None, eyebrow: str = ""):
    """One finding, chart on the right where one exists."""
    s = _blank(prs)
    if eyebrow:
        _dot(s, M, 0.63, 0.16, ACCENT)
        _text(s, M + 0.3, 0.55, 6, 0.35,
              [{"text": eyebrow.upper(), "size": 11, "bold": True, "colour": ACCENT}])
    text_w = 4.9 if chart_png else W - 2 * M
    _text(s, M, 1.05, text_w, 1.5,
          [{"text": f.headline, "size": 27, "bold": True, "font": HEAD_FONT,
            "line_spacing": 1.08}])
    _text(s, M, 2.75, text_w, 3.0,
          [{"text": f.detail, "size": 13, "colour": INK, "line_spacing": 1.28}])
    if f.evidence:
        _card(s, M, 5.75, text_w, 0.82, LIGHT)
        _text(s, M + 0.28, 5.95, text_w - 0.56, 0.5,
              [{"text": f.evidence, "size": 12, "bold": True, "colour": PRIMARY}])
    if chart_png:
        cx = M + text_w + 0.5
        cw = W - M - cx
        # Centre the chart on the slide's vertical axis. Chart aspect ratios vary
        # by type, so the height is read from the image rather than assumed.
        try:
            from PIL import Image
            iw, ih = Image.open(io.BytesIO(chart_png)).size
            ch = cw * ih / iw
        except Exception:
            ch = cw * 0.5
        _image(s, chart_png, cx, max(1.1, (H - ch) / 2), cw)
    notes = f.detail
    if f.action:
        notes += "\n\nRecommended action: " + f.action
    s.notes_slide.notes_text_frame.text = notes
    return s


def slide_stat_row(prs, title: str, stats: List[dict], caption: str = ""):
    """Large number callouts. stats: [{value, label}]."""
    s = _blank(prs)
    _text(s, M, 0.55, 11, 0.8,
          [{"text": title, "size": 32, "bold": True, "font": HEAD_FONT}])
    n = len(stats)
    gap = 0.3
    card_w = (W - 2 * M - gap * (n - 1)) / n
    for i, st in enumerate(stats):
        x = M + i * (card_w + gap)
        _card(s, x, 2.0, card_w, 2.5, LIGHT)
        _text(s, x + 0.3, 2.35, card_w - 0.6, 1.1,
              [{"text": st["value"], "size": 46, "bold": True,
                "colour": ACCENT if st.get("accent") else PRIMARY, "font": HEAD_FONT}])
        _text(s, x + 0.3, 3.5, card_w - 0.6, 0.85,
              [{"text": st["label"], "size": 12, "colour": INK, "line_spacing": 1.2}])
    if caption:
        _text(s, M, 5.0, W - 2 * M, 1.4,
              [{"text": caption, "size": 13, "colour": INK, "line_spacing": 1.3}])
    s.notes_slide.notes_text_frame.text = (
        "The headline numbers, gathered in one place before the detail. " +
        (caption if caption else "Each figure is unpacked on the slides that follow."))
    return s


def slide_actions(prs, nar: Narrative):
    s = _blank(prs)
    _text(s, M, 0.55, 11, 0.8,
          [{"text": "What to do about it", "size": 34, "bold": True,
            "font": HEAD_FONT}])
    acts = [f for f in nar.top(12) if f.action][:4]
    y = 1.75
    for f in acts:
        _dot(s, M, y + 0.09, 0.16, ACCENT)
        _text(s, M + 0.34, y, W - 2 * M - 0.4, 0.4,
              [{"text": f.headline, "size": 14, "bold": True, "colour": INK}])
        _text(s, M + 0.34, y + 0.38, W - 2 * M - 0.6, 0.8,
              [{"text": f.action, "size": 12.5, "colour": PRIMARY, "line_spacing": 1.25}])
        y += 1.28
    s.notes_slide.notes_text_frame.text = (
        "Close on actions rather than findings. Each one names something the reader "
        "can change.")
    return s


def slide_method(prs, res: dict, nar: Narrative):
    s = _blank(prs)
    _bg(s, prs, INK)
    cfg = res["config"]
    q = res["quality"]["flag_summary"]["count"]
    scale = int(q.get("scale_error_x100", 0) + q.get("scale_error_div100", 0))
    _text(s, M, 0.6, 11, 0.8,
          [{"text": "How this was produced", "size": 32, "bold": True,
            "colour": ON_DARK, "font": HEAD_FONT}])

    left = [
        ("Cleaning",
         f"Missing sentinels recoded before calculation. Outliers judged against a "
         f"{cfg.quality.reference_window} period centred rolling median of each item's own "
         f"series, so a trending price is not mistaken for a fault. "
         f"{scale} scale errors repaired by rescaling rather than deleted; "
         f"{len(res['quality']['residual_outliers'])} unexplained residuals remain."),
        ("Imputation",
         f"Default {_pretty(cfg.imputation.default_method)}. " +
         ("; ".join(f"{k}: {_pretty(v)}" for k, v in cfg.imputation.by_category.items())
          or "No category overrides.")),
    ]
    right = [
        ("Aggregation",
         f"{cfg.index.formula.title()} elementary index, matched model, "
         f"{'chained' if cfg.index.chained else 'fixed base'}. Items entering or leaving "
         "between two periods are excluded from that comparison, so replacement does not "
         "enter as price change."),
        ("Limitations",
         "No quality adjustment between a departing item and its replacement, so a change "
         "in specification is treated as price change. No expenditure weights, so the "
         "aggregate is equally weighted and indicative."),
    ]
    for col, items in ((M, left), (W / 2 + 0.2, right)):
        y = 1.7
        for head, body in items:
            _text(s, col, y, W / 2 - M - 0.3, 0.35,
                  [{"text": head, "size": 15, "bold": True, "colour": ACCENT}])
            _text(s, col, y + 0.42, W / 2 - M - 0.3, 2.0,
                  [{"text": body, "size": 12, "colour": ON_DARK, "line_spacing": 1.3}])
            y += 2.5
    _text(s, M, 6.7, 11, 0.4,
          [{"text": "Configuration exported alongside this deck reproduces every figure.",
            "size": 10, "colour": MUTED, "italic": True}])
    s.notes_slide.notes_text_frame.text = (
        "Closing method slide. Use this to answer 'how do I know this is right': every "
        "setting named here is in the exported configuration file, so the analysis can be "
        "reproduced exactly, and every judgement call (imputation, formula, chaining) is a "
        "stated default rather than something inferred from the data.")
    return s


# ----------------------------------------------------------------------
def build_deck(res: dict, nar: Narrative, charts: dict, label: str = "") -> bytes:
    """Assemble the deck from whatever the narrative actually found."""
    from .charts import to_png

    png = {k: to_png(v) for k, v in charts.items()}
    prs = Presentation()
    prs.slide_width, prs.slide_height = Inches(W), Inches(H)

    slide_title(prs, nar, label or res["config"].label)
    slide_contents(prs, nar)

    # Headline numbers
    I, yoy = res["indices"], res["inflation"]
    stats = []
    if "All items" in I.columns:
        years = (I.index[-1] - I.index[0]).days / 365.25
        stats.append({"value": f"{I['All items'].iloc[-1]:.0f}",
                      "label": f"All items index at {I.index[-1]:%b %Y}, "
                               f"{I.index[0]:%b %Y} = 100"})
        stats.append({"value": f"{((I['All items'].iloc[-1] / 100) ** (1 / years) - 1) * 100:.1f}%",
                      "label": "Average annual rate of change"})
        if yoy["All items"].notna().any():
            s_ = yoy["All items"].dropna()
            stats.append({"value": f"{s_.max():.1f}%", "accent": True,
                          "label": f"Peak twelve period rate, {s_.idxmax():%b %Y}"})
    q = res["quality"]["flag_summary"]["count"]
    scale = int(q.get("scale_error_x100", 0) + q.get("scale_error_div100", 0))
    if scale:
        stats.append({"value": f"{scale}", "accent": True,
                      "label": "Data faults detected and repaired"})
    if stats:
        slide_stat_row(prs, "The headline numbers", stats[:4],
                       "Figures are produced from the cleaned collection using a matched "
                       "model index. The aggregate is equally weighted, as no expenditure "
                       "weights were supplied.")

    # One slide per material finding, in ranked order, deduplicating charts
    eyebrow = {"quality": "Data quality", "structure": "Sample structure",
               "trend": "Price trend", "seasonal": "Seasonality",
               "method": "Method"}
    used_charts, made = set(), 0
    for f in nar.findings:
        if made >= 7:
            break
        chart = png.get(f.chart) if f.chart and f.chart not in used_charts else None
        if f.chart and chart:
            used_charts.add(f.chart)
        if f.importance < 70 and not chart:
            continue
        slide_finding(prs, f, chart, eyebrow.get(f.kind, ""))
        made += 1

    slide_actions(prs, nar)
    slide_method(prs, res, nar)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()
